### ISSUE TITLE
Expand Automatic Type Finding

### ISSUE THREAD

**Issue by adammeaney** [dalton-baker/DepRegAttributes#1]
Personally, I believe that the Register attributes should be able to find the interface that is on the class and automagically register as that.

In the register services, it would just take a bit more type work to be like "Do I have an interface on here" and register as that and the implementation instead, if you just use the empty attribute.

**Comment by dalton-baker** [comment]
Good suggestion,
I updated this to find an interface that contains the same name as a the class it's on. 

For example:
```c#
public interface IClassName { }

[RegisterTransient]
public class ClassName : IClassName { }
```
This will be registered as an IClassName. If you provide any interfaces as a parameter to the attribute this behavior will not happen.

**Comment by adammeaney** [comment]
I would suggest you have it register as ClassName as well, not just IClassName. Maybe they wanted it registering as the concrete type as well.

Something to consider.

Side Note: The test files in the linked commit are misspelled.
